services:
  nginx:
    image: nginx:latest
    container_name: web_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    container_name: web_php
    restart: always
    volumes:
      - ./app:/var/www/html

  mariadb:
    image: mariadb:10.6
    container_name: web_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: webdagang
      MYSQL_USER: dagang
      MYSQL_PASSWORD: dagang123
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web_pma
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "9090:80"

volumes:
  dbdata:


docker compose up -d
